name: Automated Selenium Test

on:
  schedule:
    # Ejecutar diariamente a las 19:00 GMT+1
    - cron: '0 18 * * *' # Hora UTC (GMT+1 es UTC+1, por eso usamos 18 aquí)
  workflow_dispatch:
    inputs:
      test_case:
        description: "Specify the test case(s) to run (e.g., C90, C15 or all for all test cases)"
        required: true
        default: "all"

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Determine job name
        id: job-name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::set-output name=job_name::Manual Selenium Test"
          else
            echo "::set-output name=job_name::Automated Selenium Test"

      - name: Display job name
        run: |
          echo "Job Name: ${{ steps.job-name.outputs.job_name }}"

      - name: Run specified test cases
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          TEST_CASES="${{ github.event.inputs.test_case }}"
          echo "Test case(s) input: $TEST_CASES"
          
          if [ "$TEST_CASES" = "all" ]; then
            echo "Running all tests..."
            node run-all-tests.js
          else
            IFS=',' read -ra TEST_ARRAY <<< "$TEST_CASES" # Split by comma
            for TEST_CASE in "${TEST_ARRAY[@]}"; do
              TEST_CASE=$(echo "$TEST_CASE" | xargs) # Trim spaces
              if [ -f "testCases/$TEST_CASE.js" ]; then
                echo "Found file: testCases/$TEST_CASE.js"
                chmod +x testCases/$TEST_CASE.js
                echo "Executing test case $TEST_CASE..."
                node -e "require('./testCases/$TEST_CASE')();"
                if [ $? -ne 0 ]; then
                  echo "Execution of $TEST_CASE.js failed"
                  exit 1
                fi
                echo "Execution of $TEST_CASE.js completed successfully"
              else
                echo "Test case not found: $TEST_CASE"
                echo "Available test cases in testCases directory:"
                ls -l testCases/
                exit 1
              fi
            done
          fi