name: Run Selenium Tests on BrowserStack

on:
  workflow_dispatch:    # Permite que los tests se ejecuten manualmente
  schedule:
    - cron: '0 19 * * *'  # Ejecuta los tests todos los días a las 7 p.m. (UTC)

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Usamos la versión más reciente de checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Usamos la versión más reciente de setup-node
        with:
          node-version: '20'  # Especificamos que queremos usar Node.js 16

      - name: Install dependencies
        run: npm install  # Este paso instala todas las dependencias definidas en package.json

      - name: Run tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: "fzuniga_kU2wfa"
          BROWSERSTACK_ACCESS_KEY: "PDSWH3QTgRyFqVWFR1sx"
        run: |
          node my-selenium-tests.js  
